apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- namespace.yaml
- helmrelease.yaml
- issuers/self-signed.yaml
configurations:
- kustomizeconfig.yaml
