apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-system
bases:
- ../../base/traefik-proxy
configMapGenerator:
- name: traefik-values
  files:
  - values.yaml=values.yaml
patchesStrategicMerge:
- helmrelease.yaml
